import { v4 as uuidv4 } from 'uuid';

export default [
  {
    id: uuidv4(),
    avatarUrl: '/images/table/oragon.png',
    companyName: 'Oragon',
    type: 'Enterprise',
    applications: '12',
    phoneScreen: '7',
    inPerson: '5',
    offers: '2',
  },
  {
    id: uuidv4(),
    avatarUrl: '/images/table/treegos.png',
    companyName: 'Treegos',
    type: 'Startup',
    applications: '12',
    phoneScreen: '7',
    inPerson: '5',
    offers: '2',
  },
  {
    id: uuidv4(),
    avatarUrl: '/images/table/google.png',
    companyName: 'Google',
    type: 'Corporation',
    applications: '12',
    phoneScreen: '7',
    inPerson: '5',
    offers: '2',
  },
  {
    id: uuidv4(),
    avatarUrl: '/images/table/oragon.png',
    companyName: 'Oragon',
    type: 'Enterprise',
    applications: '12',
    phoneScreen: '7',
    inPerson: '5',
    offers: '2',
  },
  {
    id: uuidv4(),
    avatarUrl: '/images/table/treegos.png',
    companyName: 'Treegos',
    type: 'Startup',
    applications: '12',
    phoneScreen: '7',
    inPerson: '5',
    offers: '2',
  },
  {
    id: uuidv4(),
    avatarUrl: '/images/table/google.png',
    companyName: 'Google',
    type: 'Corporation',
    applications: '12',
    phoneScreen: '7',
    inPerson: '5',
    offers: '2',
  },
];
